version: "3.9"

services:
  munoz-app:
    image: ghcr.io/bcspndamianc/flask-cicd-project:munoz-1.0.5
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.munoz.entrypoints=http'
        - 'traefik.http.routers.munoz.rule=Host(`munoz.byronrm.com`)'
        - 'traefik.http.middlewares.munoz-https-redirect.redirectscheme.scheme=https'
        - 'traefik.http.routers.munoz.middlewares=munoz-https-redirect'
        - 'traefik.http.routers.munoz-secure.entrypoints=https'
        - 'traefik.http.routers.munoz-secure.rule=Host(`munoz.byronrm.com`)'
        - 'traefik.http.routers.munoz-secure.tls=true'
        - 'traefik.http.routers.munoz-secure.tls.certresolver=http'
        - 'traefik.http.routers.munoz-secure.service=munoz'
        - 'traefik.http.services.munoz.loadbalancer.server.port=5000'
        - 'traefik.docker.network=traefik-public'
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true